final Map<String, List<String>> phrasesData = {
  'Numbers': [
    'Zero',
    'One',
    'Two',
    'Three',
    'Four',
    'Five',
    'Six',
    'Seven',
    'Eight',
    'Nine',
    'Ten',
  ],
  'Time & Date': [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday',
    'Weekday',
    'Weekend',
    'January',
    'February',
  ],
  'Colors': [
    'Red',
    'Blue',
    'Green',
    'Yellow',
    'Black',
    'White',
    'Purple',
    'Pink',
  ],
  'Greetings': [
    'Hello',
    'Good morning',
    'Good afternoon',
    'Good night',
    'How are you?',
    'Nice to meet you',
  ],
  'Directions': [
    'Go straight',
    'Turn left',
    'Turn right',
    'Stop',
    'Cross the street',
    'At the corner',
  ],
  'Shopping': [
    'How much is this?',
    'Can I try it on?',
    'I want to buy this',
    'Do you have another size?',
    'It’s too expensive',
    'Can you give me a discount?',
  ],
};
